/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.BukuController;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Maan
 */
public class ManajemenBukuPage extends javax.swing.JFrame {

    /**
     * Creates new form DashboardPage
     */
    public int IdBuku;
    BukuController bc;
    public ManajemenBukuPage() {
        initComponents();
        
        this.IdBuku = IdBuku;

        bc = new BukuController(this);
        bc.isiTabelManajemenBukuPage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jJudulField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jGenreField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTahunField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPenulisField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLink_CoverField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPinjamBukuButton = new javax.swing.JButton();
        jRiwayatPeminjamanButton = new javax.swing.JButton();
        jManajemenBukuButton = new javax.swing.JButton();
        jLogoutButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBuku = new javax.swing.JTable();
        jButtonTambah = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jLabelCover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CRUD Buku");

        jLabel2.setText("Judul Buku");

        jLabel3.setText("Genre");

        jLabel4.setText("Tahun");

        jLabel5.setText("Penulis");

        jLabel6.setText("Link Cover");

        jPinjamBukuButton.setText("Pinjam Buku");
        jPinjamBukuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPinjamBukuButtonActionPerformed(evt);
            }
        });

        jRiwayatPeminjamanButton.setText("Riwayat Peminjaman");
        jRiwayatPeminjamanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRiwayatPeminjamanButtonActionPerformed(evt);
            }
        });

        jManajemenBukuButton.setBackground(new java.awt.Color(105, 127, 98));
        jManajemenBukuButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jManajemenBukuButton.setForeground(new java.awt.Color(255, 255, 102));
        jManajemenBukuButton.setText("Manajemen Buku");
        jManajemenBukuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jManajemenBukuButtonActionPerformed(evt);
            }
        });

        jLogoutButton.setText("Logout");
        jLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutButtonActionPerformed(evt);
            }
        });

        jTableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableBuku);

        jButtonTambah.setBackground(new java.awt.Color(0, 255, 51));
        jButtonTambah.setText("Tambah");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });

        jButtonUpdate.setBackground(new java.awt.Color(255, 255, 102));
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonHapus.setBackground(new java.awt.Color(255, 0, 0));
        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonClear.setBackground(new java.awt.Color(255, 0, 0));
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jLabel7.setText("Status");

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Dipinjam", "Dihapus" }));
        jComboBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPinjamBukuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRiwayatPeminjamanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jManajemenBukuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLogoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonTambah)
                                .addGap(61, 61, 61)
                                .addComponent(jButtonUpdate)
                                .addGap(56, 56, 56)
                                .addComponent(jButtonHapus)
                                .addGap(42, 42, 42)
                                .addComponent(jButtonClear)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(83, 83, 83))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLink_CoverField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                                .addComponent(jPenulisField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTahunField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jGenreField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jJudulField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(71, 71, 71)))
                                .addComponent(jLabelCover, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(137, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jPinjamBukuButton)
                        .addGap(18, 18, 18)
                        .addComponent(jRiwayatPeminjamanButton)
                        .addGap(26, 26, 26)
                        .addComponent(jManajemenBukuButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLogoutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jJudulField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jGenreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTahunField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPenulisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLink_CoverField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelCover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonUpdate)
                                    .addComponent(jButtonHapus)
                                    .addComponent(jButtonClear)
                                    .addComponent(jButtonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutButtonActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(null, "Yakin Ingin Logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        
        if(konfirmasi == JOptionPane.YES_OPTION) {
            LoginPage loginPage = new LoginPage();
            loginPage.setVisible(true);
            loginPage.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_jLogoutButtonActionPerformed

    private void jManajemenBukuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jManajemenBukuButtonActionPerformed
        // TODO add your handling code here:
//        ManajemenBukuPage manajemenBukuPage = new ManajemenBukuPage();
//        manajemenBukuPage.setVisible(true);
//        manajemenBukuPage.setLocationRelativeTo(null);
//        this.dispose();
    }//GEN-LAST:event_jManajemenBukuButtonActionPerformed

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        // TODO add your handling code here:
        bc.insert();
        bc.isiTabelManajemenBukuPage();
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        bc.update();
        bc.isiTabelManajemenBukuPage();
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTableBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBukuMouseClicked
        // TODO add your handling code here:
        int baris = jTableBuku.getSelectedRow();
        
        jJudulField.setText(jTableBuku.getValueAt(baris, 1).toString());
        jGenreField.setText(jTableBuku.getValueAt(baris, 2).toString());
        jTahunField.setText(jTableBuku.getValueAt(baris, 3).toString());
        jPenulisField.setText(jTableBuku.getValueAt(baris, 4).toString());
        jLink_CoverField.setText(jTableBuku.getValueAt(baris, 5).toString());
        jComboBoxStatus.setSelectedItem(jTableBuku.getValueAt(baris, 6).toString());
        
        try {
            String urlCover = jTableBuku.getValueAt(baris, 5).toString();
            java.net.URL url = new java.net.URL(urlCover);
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(url);

            java.awt.Image img = icon.getImage().getScaledInstance(jLabelCover.getWidth(), jLabelCover.getHeight(), java.awt.Image.SCALE_SMOOTH);
            jLabelCover.setIcon(new javax.swing.ImageIcon(img));
            jLabelCover.setText(""); 

        } catch (Exception e) {
            jLabelCover.setIcon(null);
            jLabelCover.setText("Gambar tidak tersedia");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTableBukuMouseClicked

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        bc.delete();
        bc.isiTabelManajemenBukuPage();
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jJudulField.setText("");
        jGenreField.setText("");
        jTahunField.setText("");
        jPenulisField.setText("");
        jLink_CoverField.setText("");
        jLabelCover.setIcon(null);
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jRiwayatPeminjamanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRiwayatPeminjamanButtonActionPerformed
        // TODO add your handling code here:
        RiwayatPeminjamanPage riwayatPeminjamanPage = new RiwayatPeminjamanPage();
        riwayatPeminjamanPage.setVisible(true);
        riwayatPeminjamanPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jRiwayatPeminjamanButtonActionPerformed

    private void jPinjamBukuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPinjamBukuButtonActionPerformed
        // TODO add your handling code here:
        DashboardPage dashboardPage = new DashboardPage();
        dashboardPage.setVisible(true);
        dashboardPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jPinjamBukuButtonActionPerformed

    private void jComboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManajemenBukuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManajemenBukuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManajemenBukuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManajemenBukuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManajemenBukuPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JTextField jGenreField;
    private javax.swing.JTextField jJudulField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCover;
    private javax.swing.JTextField jLink_CoverField;
    private javax.swing.JButton jLogoutButton;
    private javax.swing.JButton jManajemenBukuButton;
    private javax.swing.JTextField jPenulisField;
    private javax.swing.JButton jPinjamBukuButton;
    private javax.swing.JButton jRiwayatPeminjamanButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBuku;
    private javax.swing.JTextField jTahunField;
    // End of variables declaration//GEN-END:variables

    public JTable getjTableBuku() {
        return jTableBuku;
    }

    public void setjTableBuku(JTable jTableBuku) {
        this.jTableBuku = jTableBuku;
    }

    public JTextField getjGenreField() {
        return jGenreField;
    }

    public void setjGenreField(JTextField jGenreField) {
        this.jGenreField = jGenreField;
    }

    public JTextField getjJudulField() {
        return jJudulField;
    }

    public void setjJudulField(JTextField jJudulField) {
        this.jJudulField = jJudulField;
    }

    public JTextField getjLink_CoverField() {
        return jLink_CoverField;
    }

    public void setjLink_CoverField(JTextField jLink_CoverField) {
        this.jLink_CoverField = jLink_CoverField;
    }

    public JTextField getjPenulisField() {
        return jPenulisField;
    }

    public void setjPenulisField(JTextField jPenulisField) {
        this.jPenulisField = jPenulisField;
    }

    public JTextField getjTahunField() {
        return jTahunField;
    }

    public void setjTahunField(JTextField jTahunField) {
        this.jTahunField = jTahunField;
    }

    public JComboBox<String> getjComboBoxStatus() {
        return jComboBoxStatus;
    }

    public void setjComboBoxStatus(JComboBox<String> jComboBoxStatus) {
        this.jComboBoxStatus = jComboBoxStatus;
    }

    public JLabel getjLabelCover() {
        return jLabelCover;
    }

    public void setjLabelCover(JLabel jLabelCover) {
        this.jLabelCover = jLabelCover;
    }
    
    
}
